apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    type: mysql
spec:
  containers:
  - name: mysql
    image: mysql:5.6
    env:
    - name: MYSQL_ROOT_PASSWORD
      # string type으로 지정해야 작동함
      value: "123456"
