apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  # 복제 개수 1->3
  replicas: 3
  selector:
    matchLabels:
      type: nginx
  template:
    metadata:
      labels:
        type: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        livenessProbe:
          httpGet:
            path: /
            port: 80