apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: whoami-rs
spec:
  # 복제 개수
  replicas: 1
  # repicaset 입장에서 pod이 있는지 없는지 판단하기 위한 부분
  selector:
    # label로 pod 찾기 : type은 app이면서 service는 whoami를 가지고있는 pod 찾기
    matchLabels:
      type: app
      service: whoami
  # 만약 pod을 못찾았다면 pod 생성
  template:
    metadata:
      labels:
        type: app
        service: whoami
    spec:
      containers:
      - name: whoami
        image: subicura/whoami:1
        livenessProbe:
          httpGet:
            path: /
            port: 4567